version: '3.7'

services:
  section-management:
    image: ghcr.io/stacs/section-management:latest
    networks:
      - collab-ingress-test
    environment:
      VIRTUAL_HOST_WEIGHT: 5
      VIRTUAL_HOST: '/lts-section-management/*'
      SERVICE_PORTS: 8080
      SPRING_PROFILES_ACTIVE: dev
    secrets:
      - source: dev_db_url
        target: db.url
      - source: dev_db_user
        target: db.user
      - source: dev_db_pass
        target: db.pass
      - source: dev_canvas_api_url
        target: canvas.apiUrl
      - source: dev_canvas_api_token
        target: canvas.apiToken
      - source: dev_boomi_api_url
        target: boomi.apiUrl
      - source: dev_boomi_api_token
        target: boomi.apiToken

networks:
  collab-ingress-test:
    external: true
    name: collab20-test


secrets:
  dev_db_url:
    external: true
  dev_db_user:
    external: true
  dev_db_pass:
    external: true
  dev_canvas_api_url:
    external: true
  dev_canvas_api_token:
    external: true
  dev_boomi_api_url:
    external: true
  dev_boomi_api_token:
    external: true
