version: '3.7'

services:
  roster-management:
    image: ghcr.io/stacs/roster-management:latest
    networks:
      - collab-ingress-prod
    environment:
      VIRTUAL_HOST_WEIGHT: 5
      VIRTUAL_HOST: '/lts-roster-management/*'
      SERVICE_PORTS: 8080
      SPRING_PROFILES_ACTIVE: prod
    secrets:
      - source: prod_db_url
        target: db.url
      - source: prod_db_user
        target: db.user
      - source: prod_db_pass
        target: db.pass
      - source: prod_canvas_api_url
        target: canvas.apiUrl
      - source: prod_canvas_api_token
        target: canvas.apiToken
      - source: prod_boomi_api_url
        target: boomi.apiUrl
      - source: prod_boomi_api_token
        target: boomi.apiToken

networks:
  collab-ingress-prod:
    external: true
    name: collab20-prod

secrets:
  prod_db_url:
    external: true
  prod_db_user:
    external: true
  prod_db_pass:
    external: true
  prod_canvas_api_url:
    external: true
  prod_canvas_api_token:
    external: true
  prod_boomi_api_url:
    external: true
  prod_boomi_api_token:
    external: true
