version: '3.7'
services:
  final-grades:
    image: ghcr.io/stacs/roster-management:latest
    networks:
      - collab-ingress-test
    environment:
      VIRTUAL_HOST_WEIGHT: 5
      VIRTUAL_HOST: '/lts-roster-management/*'
      SERVICE_PORTS: 8080
      SPRING_PROFILES_ACTIVE: dev
    secrets:
      - source: dev_db_url
        target: db.url
      - source: dev_db_user
        target: db.user
      - source: dev_db_pass
        target: db.pass
      - source: dev_canvas_api_url
        target: canvas.apiUrl
      - source: dev_canvas_api_token
        target: canvas.apiToken
