name: Build

on: [ push ]

permissions:
  id-token: write   # This is required by AWS for requesting the JWT
  contents: read    # This is required by AWS for actions/checkout

jobs:
  maven-build:
    uses: stacs/actions/.github/workflows/maven-install.yaml@v1
    secrets: inherit
  aws-deploy-dev:
    uses: stacs/actions/.github/workflows/aws-deploy-dev.yaml@v1
    needs: maven-build
    secrets: inherit
    with:
      aws_region: us-east-1
      ecr_repository_name: section-management
      ecs_task_definition_name: section-management
      ecs_container_name: section-management-container
      ecs_service_name: section-management-service
      ecs_cluster_name: lti-tools
