name: Deploy to QA

on:
  workflow_dispatch:
    inputs:
      dev_image_name:
        description: "The tag of the docker image in DEV that we want to move to QA"
        type: string
        required: true
      qa_image_name:
        description: "The tag we want to give the docker image that is being put into QA"
        type: string
        required: true

permissions:
  id-token: write   # This is required by AWS for requesting the JWT
  contents: read    # This is required by AWS for actions/checkout

jobs:
  qa-deploy:
    uses: stacs/actions/.github/workflows/aws-deploy-qa.yaml@v1
    secrets: inherit
    with:
      aws_region: us-east-1
      ecr_repository_name: section-management
      ecs_task_definition_name: section-management
      ecs_container_name: section-management-container
      ecs_service_name: section-management-service
      ecs_cluster_name: lti-tools
      dev_image_name: ${{inputs.dev_image_name}}
      qa_image_name: ${{inputs.qa_image_name}}
